// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlq--uUQEOL9lCciZyrAwPHrY_ZNAFrK0',
    appId: '1:171031787706:web:a8efbc2bfe4e7d3089ea83',
    messagingSenderId: '171031787706',
    projectId: 'pollingapp-ec325',
    authDomain: 'pollingapp-ec325.firebaseapp.com',
    databaseURL: 'https://pollingapp-ec325-default-rtdb.firebaseio.com',
    storageBucket: 'pollingapp-ec325.firebasestorage.app',
    measurementId: 'G-1XBZV08MX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxN1L9GtF9OA9gFQQBa2iKUn1CNZGgstE',
    appId: '1:171031787706:android:a437b0e5dece198c89ea83',
    messagingSenderId: '171031787706',
    projectId: 'pollingapp-ec325',
    databaseURL: 'https://pollingapp-ec325-default-rtdb.firebaseio.com',
    storageBucket: 'pollingapp-ec325.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusw2X0XjvfyvQD6_sEqbOrAlNBiJ5QIE',
    appId: '1:171031787706:ios:760578e9a3f362be89ea83',
    messagingSenderId: '171031787706',
    projectId: 'pollingapp-ec325',
    storageBucket: 'pollingapp-ec325.firebasestorage.app',
    iosBundleId: 'com.example.pollingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCusw2X0XjvfyvQD6_sEqbOrAlNBiJ5QIE',
    appId: '1:171031787706:ios:760578e9a3f362be89ea83',
    messagingSenderId: '171031787706',
    projectId: 'pollingapp-ec325',
    storageBucket: 'pollingapp-ec325.firebasestorage.app',
    iosBundleId: 'com.example.pollingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlq--uUQEOL9lCciZyrAwPHrY_ZNAFrK0',
    appId: '1:171031787706:web:49a683deeea43b9289ea83',
    messagingSenderId: '171031787706',
    projectId: 'pollingapp-ec325',
    authDomain: 'pollingapp-ec325.firebaseapp.com',
    databaseURL: 'https://pollingapp-ec325-default-rtdb.firebaseio.com',
    storageBucket: 'pollingapp-ec325.firebasestorage.app',
    measurementId: 'G-4JFS13QPQ9',
  );
}
